name: Container images

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  container_image:
    name: Build container image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Go caches
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ github.job }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ github.job }}-${{ runner.os }}-go-

    - name: Installing ko
      run: go install github.com/google/ko@v0.11.2

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICEACCOUNT_KEY }}
      if: github.event_name != 'pull_request'

    - name: Set IMAGE_TAG
      id: image-tag
      run: |
        IMAGE_TAG=sha-${GITHUB_SHA:0:7}
        [[ ${GITHUB_REF_TYPE} == "tag" ]] && IMAGE_TAG=${GITHUB_REF_NAME}
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

    - name: Publish container images and create release manifests
      env:
        KO_DOCKER_REPO: gcr.io/triggermesh/sameer/event-sources-bundle
        KOFLAGS: --jobs=2 --platform=linux/amd64,linux/arm64 --push=${{ github.event_name != 'pull_request' }}
        DIST_DIR: /tmp/dist/
      run: |
        IMAGE_TAG=${{ steps.image-tag.outputs.IMAGE_TAG }} make release
